apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "domain-exporter.fullname" . }}-config
  labels:
    {{- include "domain-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: {{ .Values.config.server.port }}
      metrics_path: {{ .Values.config.server.metrics_path | quote }}
    
    checker:
      check_interval: {{ .Values.config.checker.check_interval }}
      concurrency: {{ .Values.config.checker.concurrency }}
      timeout: {{ .Values.config.checker.timeout }}
    
    domains:
    {{- range .Values.config.domains }}
      - {{ . }}
    {{- end }}